unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on
set -g base-index 1

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# styles

gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_light="#3B4252"
green_soft="#A3BE8C"
green_soft="#81A1C1"
cyan_soft="#88C0D0"

set-option -g status-position top
set -g status-style "fg=${gray_light}, bg=default"
set -g status-left "#[fg=${green_soft}, bold] #S #[fg=${gray_light}, nobold] | "
set -g window-status-current-format "#[fg=${cyan_soft}, bold]  #[underscore]#I:#W"
